package com.example.quanlythucung.domain.model;
// Generated Aug 5, 2015 11:46:07 AM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role")
public class Role implements java.io.Serializable {

    private Integer roleId;
    private String roleName;
    private Set<UserRole> userRoles = new HashSet<UserRole>(0);

    public Role() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_Role", unique = true, nullable = false)
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Column(name = "roleName", length = 20)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }

    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }

}
